import { ModelConfig } from "./types";

export const AVAILABLE_MODELS: ModelConfig[] = [
  {
    id: "nano-banana-pro",
    owner: "google",
    name: "nano-banana-pro",
    type: "image-generation",
    description: "Efficient Nano Banana Pro model",
    price: 0.15,
    imageInputMode: "image_input",
    maxImages: 14,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
  },
  {
    id: "nano-banana",
    owner: "google",
    name: "nano-banana",
    type: "image-generation",
    description: "Efficient Nano Banana model",
    price: 0.04,
    imageInputMode: "image_input",
    maxImages: 10,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
  },
  {
    id: "flux-2-dev",
    owner: "black-forest-labs",
    name: "flux-2-dev",
    type: "image-generation",
    description: "High-quality image generation model (Dev)",
    price: 0.02,
    imageInputMode: "input_images",
    maxImages: 5,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
    supportsSafetyChecker: true,
  },
  {
    id: "flux-2-pro",
    owner: "black-forest-labs",
    name: "flux-2-pro",
    type: "image-generation",
    description: "Professional grade flux model",
    price: 0.06,
    imageInputMode: "input_images",
    maxImages: 8,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
  },
  {
    id: "flux-2-flex",
    owner: "black-forest-labs",
    name: "flux-2-flex",
    type: "image-generation",
    description: "Flexible optimized flux model",
    price: 0.12,
    imageInputMode: "input_images",
    maxImages: 10,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
  },
  {
    id: "seedream-4",
    owner: "bytedance",
    name: "seedream-4",
    type: "image-generation",
    description: "Dream-like image generation",
    price: 0.03,
    imageInputMode: "image_input",
    maxImages: 10,
    supportsAspectRatio: true,
  },
  {
    id: "seededit-3.0",
    owner: "bytedance",
    name: "seededit-3.0",
    type: "image-editing",
    description: "SeedEdit 3.0",
    price: 0.03,
    imageInputMode: "image_string",
    maxImages: 1,
  },
  {
    id: "qwen-image-2",
    owner: "qwen",
    name: "qwen-image-2",
    type: "image-editing",
    description: "Qwen Image 2 - unified generation + editing",
    price: 0.035,
    imageInputMode: "image_string",
    maxImages: 1,
    supportsAspectRatio: true,
  },
  {
    id: "qwen-image-edit-plus",
    owner: "qwen",
    name: "qwen-image-edit-plus",
    type: "image-editing",
    description: "Qwen Image Edit 2509 (v2) - multi-image editing",
    price: 0.03,
    imageInputMode: "image_array",
    maxImages: 3,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
    supportsSafetyChecker: true,
  },
  {
    id: "qwen-image-edit-plus-lora",
    owner: "qwen",
    name: "qwen-image-edit-plus-lora",
    type: "image-editing",
    description: "Qwen Image Edit 2509 + LoRA explorer",
    price: 0.03,
    imageInputMode: "image_array",
    maxImages: 3,
    supportsAspectRatio: true,
    supportsOutputFormat: true,
    supportsSafetyChecker: true,
    supportsLora: true,
  },
  {
    id: "reve-edit",
    owner: "reve",
    name: "edit",
    type: "image-editing",
    description: "Standard Reve image editor",
    price: 0.04,
    imageInputMode: "image_string",
    maxImages: 1,
  },
  {
    id: "reve-edit-fast",
    owner: "reve",
    name: "edit-fast",
    type: "image-editing",
    description: "Fast Reve image editor",
    price: 0.01,
    imageInputMode: "image_string",
    maxImages: 1,
  },
];
